export type PipelineStage = 'node_generation' | 'credential_injection' | 'connection_wiring' | 'workflow_structure'

export const VALIDATOR_RULE_IDS: number[] = Array.from({ length: 23 }, (_, i) => i + 1)

export const RULE_PIPELINE_STAGES: Record<number, PipelineStage> = {
  1: 'node_generation',
  2: 'node_generation',
  3: 'node_generation',
  4: 'node_generation',
  5: 'node_generation',
  6: 'node_generation',
  7: 'node_generation',
  8: 'node_generation',
  9: 'connection_wiring',
  10: 'connection_wiring',
  11: 'connection_wiring',
  12: 'workflow_structure',
  13: 'node_generation',
  14: 'workflow_structure',
  15: 'node_generation',
  16: 'node_generation',
  17: 'credential_injection',
  18: 'connection_wiring',
  19: 'node_generation',
  20: 'connection_wiring',
  21: 'workflow_structure',
  22: 'workflow_structure',
  23: 'node_generation',
}

export const RULE_MITIGATIONS: Record<number, string> = {
  1: 'Provide a non-empty workflow name string',
  2: 'Include at least one node in the nodes array',
  3: 'Every node must have a unique UUID v4 string as its id field',
  4: 'Ensure all node ids are unique — no two nodes can share the same id',
  5: 'Every node must have a non-empty type string',
  6: 'Every node must have a positive integer typeVersion',
  7: 'Every node must have a position array of exactly [x, y] numbers',
  8: 'Every node must have a non-empty name string',
  9: 'connections must be a plain object (use {} if no connections)',
  10: 'Every node name in connections (source and target) must exactly match a name in the nodes array',
  11: 'Every non-trigger node should have at least one incoming connection',
  12: 'Remove forbidden fields: id, active, createdAt, updatedAt, versionId, meta, tags — these are server-assigned',
  13: 'workflow.settings must be a plain object if present',
  14: 'Include at least one trigger node (e.g. scheduleTrigger, webhookTrigger, manualTrigger, or service-specific)',
  15: 'Node type strings must be fully qualified: "n8n-nodes-base.httpRequest" not just "httpRequest"',
  16: 'All node names must be unique within the workflow',
  17: 'Credentials must be an object with non-empty string id and name fields: { id: "placeholder-id", name: "My Credential" }',
  18: 'AI sub-nodes (languageModel, memory, tool) must be the CONNECTION SOURCE pointing TO the agent — not the reverse',
  19: 'Use known safe typeVersion values for each node type',
  20: 'Remove connection cycles — ensure no node can reach itself through the connection graph',
  21: 'When using webhook with responseMode "responseNode", include a respondToWebhook node in the flow',
  22: 'Ensure all required parameters are set for each node type (e.g. webhook needs httpMethod and path)',
  23: 'Use node types that exist in the n8n registry — check with kairos_sync',
}
